language: r
warnings_are_errors: true
sudo: false
cache: packages
latex: false

env:
  global:
    - CRAN: http://cloud.r-project.org

include:
  - r: release
  - r: oldrel
  - r: devel

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
